name: 📚 New Book
description: 新しく積読に加える本
labels: ["📖 Unread"]
projects: "takuma-fuji/4"
body:
  - type: input
    id: title
    attributes:
      label: 書名
      placeholder: 例）『ご冗談でしょう、ファインマンさん』
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: 例）https://~
  - type: input
    id: author
    attributes:
      label: 著者
      placeholder: Richard P. Feynman
  - type: dropdown
    id: status
    attributes:
      label: Status
      options: ["📖 Unread", "👓 Reading", "✅ Read"]
      default: 0
  - type: textarea
    id: note
    attributes:
      label: メモ・引用
      placeholder: 読みながら気づいたことをメモする
